// ==========================================================================
// Riser - Copyright (c) 2026 Squarebit LLC. All rights reserved.
//
// RiserDocument -> USDA text.
//
// The browser has no USD writer (three's USDZExporter emits ARKit meshes, not
// arbitrary prims), so we author the layer as text. That is not a workaround:
// USDA is the format's own human-readable serialization, and writing it
// ourselves is what lets us emit guide and curve prims with our own namespaced
// metadata.
//
// The output has to satisfy two independent readers, and it is written to the
// intersection of what both accept:
//
//   1. OpenUSD on the server (usd-core). The real authority.
//   2. three's USDAParser in the browser, for reading our own layer back.
//
// Constraints that follow from (2), each of them load-bearing:
//   * No `custom` qualifier - its ATTR_MATCH_REGEX only allows `uniform`.
//   * The `(` of a metadata block goes on its own line or ends the def line.
//   * Values are single-line, except arrays, which may wrap (the parser
//     accumulates until the brackets balance).
//
// This module imports nothing from three.js. It is pure text generation over
// plain data, which is what makes it exhaustively testable.
// ==========================================================================

import type { Curve, Guide, RiserDocument, SurfaceBinding, Vec3 } from './types';

/** Decimal places written for positions, normals and barycentric weights. */
const PRECISION = 7;

const ROOT_PRIM = 'Riser';
const CHARACTER_PRIM = 'Character';
const GUIDES_SCOPE = 'Guides';
const CURVES_SCOPE = 'Curves';

export const PATHS = {
  root: `/${ROOT_PRIM}`,
  character: `/${ROOT_PRIM}/${CHARACTER_PRIM}`,
  guides: `/${ROOT_PRIM}/${GUIDES_SCOPE}`,
  curves: `/${ROOT_PRIM}/${CURVES_SCOPE}`
} as const;

// -------------------------------------------------------------------------
// Value formatting
// -------------------------------------------------------------------------

/**
 * Format a number for USDA. Fixed notation only - exponent form is legal USD
 * but harder to eyeball in a diff, and these magnitudes never need it.
 */
export function fmt(n: number): string {
  if (!Number.isFinite(n)) return '0';
  if (Number.isInteger(n) && Math.abs(n) < 1e15) return String(n);
  const s = n.toFixed(PRECISION);
  // Trim trailing zeros but always leave one decimal, so the value still reads
  // as a float rather than an int.
  return s.replace(/(\.\d*?)0+$/, '$1').replace(/\.$/, '.0');
}

export function fmtVec3(v: Vec3): string {
  return `(${fmt(v[0])}, ${fmt(v[1])}, ${fmt(v[2])})`;
}

/** Quote and escape a string for USDA. */
export function quote(s: string): string {
  return `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')}"`;
}

/**
 * USD prim names must be C identifiers. The user-facing id is always written
 * separately as an attribute, so sanitising the name here loses nothing - the
 * reader takes the id from `riser:*:id`, never from the prim name.
 */
export function primName(id: string): string {
  const cleaned = id.replace(/[^A-Za-z0-9_]/g, '_');
  return /^[0-9]/.test(cleaned) ? `_${cleaned}` : cleaned || 'Unnamed';
}

/** Wrap a long array across lines. The parser rejoins on bracket balance. */
function arrayLiteral(items: string[], indent: string, perLine = 4): string {
  if (items.length === 0) return '[]';
  if (items.length <= perLine) return `[${items.join(', ')}]`;
  const lines: string[] = [];
  for (let i = 0; i < items.length; i += perLine) {
    lines.push(indent + '    ' + items.slice(i, i + perLine).join(', '));
  }
  return `[\n${lines.join(',\n')}\n${indent}]`;
}

// -------------------------------------------------------------------------
// Writer
// -------------------------------------------------------------------------

class Lines {
  private readonly out: string[] = [];

  push(indent: number, text: string): void {
    this.out.push('    '.repeat(indent) + text);
  }

  blank(): void {
    this.out.push('');
  }

  toString(): string {
    return this.out.join('\n') + '\n';
  }
}

export interface WriteOptions {
  /**
   * Emit a `# generated by` banner. Off in tests so fixtures stay stable
   * regardless of when they were produced.
   */
  banner?: boolean;
}

export function writeUsda(doc: RiserDocument, options: WriteOptions = {}): string {
  const L = new Lines();

  // ---- Stage metadata -------------------------------------------------
  // `(` on its own line: three's parser keys the block off a line that ends
  // with '(' and takes the preceding line as the block's owner.
  L.push(0, '#usda 1.0');
  L.push(0, '(');
  L.push(1, `defaultPrim = ${quote(ROOT_PRIM)}`);
  L.push(1, `metersPerUnit = ${fmt(doc.metersPerUnit)}`);
  L.push(1, `upAxis = ${quote(doc.upAxis)}`);
  L.push(1, `doc = ${quote(`Riser document: ${doc.name}`)}`);
  L.push(0, ')');
  L.blank();

  if (options.banner) {
    L.push(0, `# Generated by Riser ${doc.docVersion}. Edits here are safe to`);
    L.push(0, '# re-import; the app reads its own riser: attributes back.');
    L.blank();
  }

  // ---- Root ------------------------------------------------------------
  L.push(0, `def Xform ${quote(ROOT_PRIM)} (`);
  L.push(1, 'kind = "assembly"');
  L.push(0, ')');
  L.push(0, '{');
  L.push(1, `string riser:docVersion = ${quote(doc.docVersion)}`);
  L.push(1, `string riser:template = ${quote(doc.templateId)}`);
  L.push(1, `string riser:name = ${quote(doc.name)}`);
  L.blank();

  // ---- The character, by reference -------------------------------------
  // A reference rather than a copy: the layer stays small, the asset stays
  // authoritative, and the server resolves it against real geometry.
  L.push(1, `def ${quote(CHARACTER_PRIM)} (`);
  L.push(2, `prepend references = @${doc.characterRef}@`);
  L.push(1, ')');
  L.push(1, '{');
  L.push(1, '}');
  L.blank();

  // ---- Guides ----------------------------------------------------------
  L.push(1, `def Scope ${quote(GUIDES_SCOPE)}`);
  L.push(1, '{');
  for (const guide of doc.guides) {
    writeGuide(L, guide);
  }
  L.push(1, '}');
  L.blank();

  // ---- Curves ----------------------------------------------------------
  L.push(1, `def Scope ${quote(CURVES_SCOPE)}`);
  L.push(1, '{');
  for (const curve of doc.curves) {
    writeCurve(L, curve);
  }
  L.push(1, '}');

  L.push(0, '}');
  return L.toString();
}

function writeGuide(L: Lines, guide: Guide): void {
  L.push(2, `def Xform ${quote(primName(guide.id))}`);
  L.push(2, '{');

  // Idiomatic USD placement, so the guide shows up correctly in usdview and
  // any other USD tool, not just ours.
  L.push(3, `double3 xformOp:translate = ${fmtVec3(guide.position)}`);
  L.push(3, 'uniform token[] xformOpOrder = ["xformOp:translate"]');
  L.blank();

  L.push(3, `uniform token riser:guide:id = ${quote(guide.id)}`);
  L.push(3, `uniform token riser:guide:group = ${quote(guide.group)}`);
  L.push(3, `float3 riser:guide:normal = ${fmtVec3(guide.normal)}`);
  // Provenance travels with the layer so the server knows which positions a
  // person stood behind and which the app guessed.
  L.push(3, `uniform token riser:guide:source = ${quote(guide.source)}`);
  L.push(3, `float riser:guide:confidence = ${fmt(guide.confidence)}`);

  if (guide.binding) {
    writeBinding(L, 3, 'riser:guide', guide.binding);
  } else {
    // Explicit rather than absent, so a reader can tell "placed free in space"
    // apart from "written by an older version that had no bindings".
    L.push(3, 'uniform token riser:guide:bound = "none"');
  }

  L.push(2, '}');
}

function writeBinding(
  L: Lines,
  indent: number,
  ns: string,
  binding: SurfaceBinding
): void {
  L.push(indent, `uniform token ${ns}:bound = "surface"`);
  L.push(indent, `rel ${ns}:bindPrim = <${binding.primPath}>`);
  L.push(indent, `int ${ns}:faceIndex = ${binding.faceIndex}`);
  L.push(indent, `float3 ${ns}:barycentric = ${fmtVec3(binding.barycentric)}`);
  L.push(indent, `float3 ${ns}:offset = ${fmtVec3(binding.offset)}`);
}

function writeCurve(L: Lines, curve: Curve): void {
  const indent = '        ';
  const points = curve.points;

  L.push(2, `def BasisCurves ${quote(primName(curve.id))}`);
  L.push(2, '{');

  // A real BasisCurves prim, so the curve is renderable by any USD tool.
  L.push(3, 'uniform token type = "cubic"');
  L.push(3, 'uniform token basis = "bspline"');
  L.push(3, `uniform token wrap = ${quote(curve.closed ? 'periodic' : 'nonperiodic')}`);
  L.push(3, `int[] curveVertexCounts = [${points.length}]`);
  L.push(
    3,
    `point3f[] points = ${arrayLiteral(
      points.map((p) => fmtVec3(p.position)),
      indent
    )}`
  );
  L.push(3, `float[] widths = [${fmt(curve.width)}]`);
  L.push(3, 'uniform token[] primvars:widths:interpolation = ["constant"]');
  L.blank();

  L.push(3, `uniform token riser:curve:id = ${quote(curve.id)}`);
  L.push(3, `uniform token riser:curve:group = ${quote(curve.group)}`);
  L.push(3, `bool riser:curve:closed = ${curve.closed ? 'true' : 'false'}`);
  L.push(
    3,
    `float3[] riser:curve:normals = ${arrayLiteral(
      points.map((p) => fmtVec3(p.normal)),
      indent
    )}`
  );

  // Per-point bindings, stored as parallel arrays. A point with no binding
  // writes an empty prim path and a face index of -1, which the reader treats
  // as "free in space" - the same distinction the guides make.
  L.push(
    3,
    `string[] riser:curve:bindPrims = ${arrayLiteral(
      points.map((p) => quote(p.binding?.primPath ?? '')),
      indent,
      2
    )}`
  );
  L.push(
    3,
    `int[] riser:curve:faceIndices = ${arrayLiteral(
      points.map((p) => String(p.binding?.faceIndex ?? -1)),
      indent,
      8
    )}`
  );
  L.push(
    3,
    `float3[] riser:curve:barycentrics = ${arrayLiteral(
      points.map((p) => fmtVec3(p.binding?.barycentric ?? [0, 0, 0])),
      indent
    )}`
  );
  L.push(
    3,
    `float3[] riser:curve:offsets = ${arrayLiteral(
      points.map((p) => fmtVec3(p.binding?.offset ?? [0, 0, 0])),
      indent
    )}`
  );

  L.push(2, '}');
}
